### ISSUE TITLE
[onetrueslash] error when using `/` in dms.

### ISSUE THREAD

**Issue by ltzmax** [zephyrkul/FluffyCogs#59]
Any slash commands you try to use in dms will error the following. And this happens when you start with `/botname command` 
```py
┌──────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────┐
│ C:\Users\maxbo\redenv\lib\site-packages\discord\app_commands\tree.py:590 in wrapper                                                                        │
│ > 590                 await self.call(interaction)                                                                                                         │
│ C:\Users\maxbo\redenv\lib\site-packages\discord\app_commands\tree.py:706 in call                                                                           │
│ > 706             await command._invoke_autocomplete(interaction, focused, namespace)                                                                      │
│ C:\Users\maxbo\redenv\lib\site-packages\discord\app_commands\commands.py:425 in _invoke_autocomplete                                                       │
│ >  425             choices = await param.autocomplete(interaction, value, namespace)                                                                       │
│ C:\Users\maxbo\Documents\discord\cogs\CogManager\cogs\onetrueslash\commands.py:64 in onetrueslash_command_autocomplete                                     │
│ > 64     ctx = InterContext.from_interaction(interaction)                                                                                                  │
│ C:\Users\maxbo\Documents\discord\cogs\CogManager\cogs\onetrueslash\context.py:38 in from_interaction                                                       │
│ > 38         message = InterMessage.from_interaction(interaction)                                                                                          │
│ C:\Users\maxbo\Documents\discord\cogs\CogManager\cogs\onetrueslash\message.py:37 in from_interaction                                                       │
│ > 37         self.channel.__class__ = type(                                                                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: __class__ assignment: 'InterChannel' object layout differs from 'PartialMessageable'
```
Also got this:
```py
Ignoring exception in command 'neobot':
Traceback (most recent call last):
  File "C:\Users\maxbo\redenv\lib\site-packages\discord\app_commands\commands.py", line 391, in _invoke_with_namespace
    return await self._callback(interaction, **values)  # type: ignore
  File "C:\Users\maxbo\Documents\discord\cogs\CogManager\cogs\onetrueslash\commands.py", line 27, in onetrueslash
    ctx = InterContext.from_interaction(interaction, recreate_message=True)
  File "C:\Users\maxbo\Documents\discord\cogs\CogManager\cogs\onetrueslash\context.py", line 38, in from_interaction
    message = InterMessage.from_interaction(interaction)
  File "C:\Users\maxbo\Documents\discord\cogs\CogManager\cogs\onetrueslash\message.py", line 37, in from_interaction
    self.channel.__class__ = type(
TypeError: __class__ assignment: 'InterChannel' object layout differs from 'PartialMessageable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxbo\redenv\lib\site-packages\discord\app_commands\tree.py", line 710, in call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\maxbo\redenv\lib\site-packages\discord\app_commands\commands.py", line 405, in _invoke_with_namespace
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'neobot' raised an exception: TypeError: __class__ assignment: 'InterChannel' object layout differs from 'PartialMessageable'
[14:54:32] CRITICAL [red.main] Caught unhandled exception in <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at C:\Users\maxbo\redenv\lib\site-packages\discord\app_commands\tree.py:588> exception=TypeError("__class__ assignment: 'InterChannel' object layout differs from 'PartialMessageable'")>:
Task exception was never retrieved
```` 

Sentry log: https://sentry.io/share/issue/7bbdfe6b7bb44aba8163ef65b8cb83b5/

**Comment by zephyrkul** [comment]
Fixed yesterday with https://github.com/zephyrkul/FluffyCogs/commit/12438926947a429bfeb55b1fd3c9f3debfe05ef9.
(The fix was posted the fix yesterday but I couldn't test it until this morning.)
