### ISSUE TITLE
[Act] Traceback

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [zephyrkul/FluffyCogs#7]
I get this whenever a user uses a command they don't have perms for. (for instance this is a user using the [p]kick command without any mod perms)
```
Traceback (most recent call last):
  File "/home/Ianardodiscord/Ianardo/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/home/Ianardodiscord/DiscordBot/cogs/CogManager/cogs/act/act.py", line 219, in on_message
    if await ctx.command.can_run(ctx):
  File "/home/Ianardodiscord/Ianardo/lib/python3.7/site-packages/redbot/core/commands/commands.py", line 230, in can_run
    ret = await super().can_run(ctx)
  File "/home/Ianardodiscord/Ianardo/lib/python3.7/site-packages/discord/ext/commands/core.py", line 920, in can_run
    raise CheckFailure('The global check functions for command {0.qualified_name} failed.'.format(self))
discord.ext.commands.errors.CheckFailure: The global check functions for command kick failed.
```

**Comment by zephyrkul** [comment]
I get the feeling that this is a bug that the core Red devs should also know about (`can_run` shouldn't raise and instead should return `False`, and if the behavior was intentionally changed there should have been a breaking change notice), I'll add a try-catch to that line anyway.
