### ISSUE TITLE
OneTrueSlash doesnt work with help

### ISSUE THREAD

**Issue by NanashiTheNameless** [Zephyrkul/FluffyCogs#75]
```
[2024-03-10 20:42:45] [INFO] red.vex.cmdlog: Text command 'slash sync' ran by 221701506561212416 (namelessnanashi) in our DMs.
[2024-03-10 20:46:38] [INFO] red.vex.cmdlog: Slash command [namelessbot] ran by 221701506561212416 [BasicDiscordObject(id=221701506561212416, name='namelessnanashi')] in our DMs.
[2024-03-10 20:46:39] [INFO] red.vex.cmdlog: Text command 'ping' ran by 221701506561212416 (namelessnanashi) in our DMs.
[2024-03-10 20:47:04] [INFO] red.vex.cmdlog: Slash command [namelessbot] ran by 221701506561212416 [BasicDiscordObject(id=221701506561212416, name='namelessnanashi')] in channel 1109581264392040450 [general] in guild 1109581263637057659 [0.0]
[2024-03-10 20:47:04] [ERROR] red: Exception in command 'help'
Traceback (most recent call last):
  File "/root/redenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/onetrueslash/commands.py", line 53, in onetrueslash
    await interaction.client.send_help_for(
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1288, in send_help_for
    return await self._help_formatter.send_help(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 252, in send_help
    await self.format_bot_help(ctx, help_settings=help_settings)
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 640, in format_bot_help
    coms = await self.get_bot_help_mapping(ctx, help_settings=help_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 296, in get_bot_help_mapping
    cm = await self.get_cog_help_mapping(ctx, cog, help_settings=help_settings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in get_cog_help_mapping
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in <dictcomp>
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 728, in help_filter_func
    if await obj.can_see(ctx) and getattr(obj, "enabled", True):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 542, in can_see
    can_run = await self.can_run(
              ^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 429, in can_run
    ret = await super().can_run(ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 524, in can_run
    return await self.app_command._check_can_run(ctx.interaction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 418, in _check_can_run
    if self.wrapped.checks and not await async_all(f(ctx) for f in self.wrapped.checks):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/utils.py", line 705, in async_all
    elem = await elem
           ^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/conversationgames/core.py", line 46, in _predicate
    rating = await ctx.cog.config.guild(ctx.guild).rating()  # type: ignore
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'config'
[2024-03-10 20:47:04] [ERROR] red: Exception in command 'namelessbot'
Traceback (most recent call last):
  File "/root/redenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/onetrueslash/commands.py", line 53, in onetrueslash
    await interaction.client.send_help_for(
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1288, in send_help_for
    return await self._help_formatter.send_help(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 252, in send_help
    await self.format_bot_help(ctx, help_settings=help_settings)
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 640, in format_bot_help
    coms = await self.get_bot_help_mapping(ctx, help_settings=help_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 296, in get_bot_help_mapping
    cm = await self.get_cog_help_mapping(ctx, cog, help_settings=help_settings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in get_cog_help_mapping
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in <dictcomp>
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 728, in help_filter_func
    if await obj.can_see(ctx) and getattr(obj, "enabled", True):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 542, in can_see
    can_run = await self.can_run(
              ^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 429, in can_run
    ret = await super().can_run(ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 524, in can_run
    return await self.app_command._check_can_run(ctx.interaction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 418, in _check_can_run
    if self.wrapped.checks and not await async_all(f(ctx) for f in self.wrapped.checks):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/utils.py", line 705, in async_all
    elem = await elem
           ^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/conversationgames/core.py", line 46, in _predicate
    rating = await ctx.cog.config.guild(ctx.guild).rating()  # type: ignore
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'config'
[2024-03-10 20:47:43] [INFO] red.vex.cmdlog: Slash command [namelessbot] ran by 221701506561212416 [BasicDiscordObject(id=221701506561212416, name='namelessnanashi')] in channel 1109581264392040450 [general] in guild 1109581263637057659 [0.0]
[2024-03-10 20:47:44] [INFO] red.vex.cmdlog: Text command [slash sync] ran by 221701506561212416 [namelessnanashi] with message ID 1216487678930063410 in channel 1109581264392040450 [general] in guild 1109581263637057659 [0.0]
[2024-03-10 20:47:57] [INFO] red.vex.cmdlog: Slash command [namelessbot] ran by 221701506561212416 [BasicDiscordObject(id=221701506561212416, name='namelessnanashi')] in channel 1109581264392040450 [general] in guild 1109581263637057659 [0.0]
[2024-03-10 20:47:57] [ERROR] red: Exception in command 'help'
Traceback (most recent call last):
  File "/root/redenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/onetrueslash/commands.py", line 53, in onetrueslash
    await interaction.client.send_help_for(
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1288, in send_help_for
    return await self._help_formatter.send_help(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 252, in send_help
    await self.format_bot_help(ctx, help_settings=help_settings)
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 640, in format_bot_help
    coms = await self.get_bot_help_mapping(ctx, help_settings=help_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 296, in get_bot_help_mapping
    cm = await self.get_cog_help_mapping(ctx, cog, help_settings=help_settings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in get_cog_help_mapping
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in <dictcomp>
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 728, in help_filter_func
    if await obj.can_see(ctx) and getattr(obj, "enabled", True):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 542, in can_see
    can_run = await self.can_run(
              ^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 429, in can_run
    ret = await super().can_run(ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 524, in can_run
    return await self.app_command._check_can_run(ctx.interaction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 418, in _check_can_run
    if self.wrapped.checks and not await async_all(f(ctx) for f in self.wrapped.checks):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/utils.py", line 705, in async_all
    elem = await elem
           ^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/conversationgames/core.py", line 46, in _predicate
    rating = await ctx.cog.config.guild(ctx.guild).rating()  # type: ignore
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'config'
[2024-03-10 20:47:57] [ERROR] red: Exception in command 'namelessbot'
Traceback (most recent call last):
  File "/root/redenv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/onetrueslash/commands.py", line 53, in onetrueslash
    await interaction.client.send_help_for(
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1288, in send_help_for
    return await self._help_formatter.send_help(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 252, in send_help
    await self.format_bot_help(ctx, help_settings=help_settings)
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 640, in format_bot_help
    coms = await self.get_bot_help_mapping(ctx, help_settings=help_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 296, in get_bot_help_mapping
    cm = await self.get_cog_help_mapping(ctx, cog, help_settings=help_settings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in get_cog_help_mapping
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 278, in <dictcomp>
    return {
           ^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 728, in help_filter_func
    if await obj.can_see(ctx) and getattr(obj, "enabled", True):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 542, in can_see
    can_run = await self.can_run(
              ^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 429, in can_run
    ret = await super().can_run(ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 524, in can_run
    return await self.app_command._check_can_run(ctx.interaction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 418, in _check_can_run
    if self.wrapped.checks and not await async_all(f(ctx) for f in self.wrapped.checks):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/utils.py", line 705, in async_all
    elem = await elem
           ^^^^^^^^^^
  File "/root/.local/share/Red-DiscordBot/data/NamelessBot/cogs/CogManager/cogs/conversationgames/core.py", line 46, in _predicate
    rating = await ctx.cog.config.guild(ctx.guild).rating()  # type: ignore
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'config'

```

**Comment by Zephyrkul** [comment]
Does running `[p]help` directly still work for you?

**Comment by Zephyrkul** [comment]
Thanks for the report and the detailed logs. The issue should be resolved now.

**Comment by Zephyrkul** [comment]
> Really? So what was the issue?

onetrueslash is a very technical cog that messes around with internals a lot, but I'll give a basic overview for curiosity's sake.

The relevant commit is [here](https://github.com/Zephyrkul/FluffyCogs/commit/3c49ddf237dfdb344b68cefdae5bf5435bd2d222).

In short, onetrueslash's fake Context objects will "hide" the fact that they're from an Interaction so discord.py parses commands as if they were text commands (i.e. `[p]help` rather than `/bot command:help`). Previously, onetrueslash would reveal this origin when calling `help`, however there appears to be an issue with how hybrid commands' check functions are called that would incorrectly propogate certain exceptions when discord.py sees the Context as having come from an interaction. This commit changes onetrueslash to keep the Interaction origin hidden so discord.py will call command checks as if the fake Context is from a text command, retaining the behavior that one would expect from `[p]help` when run as a text command.
